graph LR
  subgraph EARTH[EARTH]
    T1[T1 Earth Ground - 6 Nodes]
    T2[T2 Earth Orbital - 51 Nodes]
  end
  subgraph DEEP[DEEP SPACE]
    T3[T3 Transit - 4 Nodes]
  end
  subgraph MARS[MARS]
    T4[T4 Mars Orbital - 13 Nodes]
    T5[T5 Mars Surface - 167 Nodes]
  end
  T1 -->|100 Mbps| T2
  T2 -->|10 Gbps ISL| T3
  T3 -->|2 to 200 Mbps| T4
  T4 -->|2 Mbps UHF| T5
  T2 -.->|Redundant L5| T3
  T3 -.->|Direct optical| T4
